/**
 * Created by tuan nguyen on 04/11/2021
 */

export const API_ROOT = 'http://localhost:8017'
// export const API_ROOT = 'https://trello-trungquandev-api.herokuapp.com'

export const MODAL_ACTION_CLOSE = 'MODAL_ACTION_CLOSE'
export const MODAL_ACTION_CONFIRM = 'MODAL_ACTION_CONFIRM'

export const USER_SELECT_POPOVER_TYPE_BOARD_MEMBERS = 'USER_SELECT_POPOVER_TYPE_BOARD_MEMBERS'
export const USER_SELECT_POPOVER_TYPE_CARD_MEMBERS = 'USER_SELECT_POPOVER_TYPE_CARD_MEMBERS'

export const CARD_MEMBERS_ACTION_PUSH = 'CARD_MEMBERS_ACTION_PUSH'
export const CARD_MEMBERS_ACTION_REMOVE = 'CARD_MEMBERS_ACTION_REMOVE'
